### ISSUE TITLE
Harvard Mirador issue

### ISSUE THREAD

**Issue by mirazoom** [lovasoa/dezoomify#250]
Trying to get maximum resolution image(14441x18334) of this: https://iiif.lib.harvard.edu/manifests/view/ids:23971462
The server url is: https://ids.lib.harvard.edu/ids/iiif/23971462/full/full/0/native.jpg but that doesn't yield max. resolution image.

Tried the json: https://ids.lib.harvard.edu/ids/iiif/23971462/info.json on dezoomify but gets stuck at 93% as bottom strip of tiles are not exactly 1024x1024 so the script fails when it tries to access a tile like this for example: https://ids.lib.harvard.edu/ids/iiif/23971462/1024,14336,1024,1024/1024,1024/0/default.jpg
instead of: https://ids.lib.harvard.edu/ids/iiif/23971462/1024,14336,1024,1024/1024,/0/default.jpg

Also note Height * Width * 4 = 1059045176 which is >500000000 Firefox limit mentioned in the FAQ so gfx.max-alloc-size needs to be set higher.

Browser:  Firefox 61.0.2 (64-bit)
Error message:
"Error: Unable to load tile.
Check that your internet connection is working and that you can access this url:
https://ids.lib.harvard.edu/ids/iiif/23971462/1024,14336,1024,1024/1024,1024/0/default.jpg
(http://ophir.alwaysdata.net/dezoomify/zoommanager.js:178)"

**Comment by dancorpse** [comment]
My loading gets stuck at 93% also...

**Comment by dancorpse** [comment]
I've encountered a couple of problems with iiif images and remain unsolved.

**Comment by mirazoo** [comment]
I saw the issues from https://github.com/lovasoa/dezoomify/issues/248 and https://github.com/lovasoa/dezoomify/issues/233 are related to this issue.

Basically the dezoomify script loads tiles starting from the top-left corner and moving along by scalefactors of the max tile size (in above example 1024x1024).
It does so correctly until it reaches the row of tiles at bottom edge  or the column of tiles at the right edge.
Because these tiles are not exactly 1024x1024 the server either refuses the request(leading to incomplete download error) or stretches the tiles to the size specified(leading to weird edge stretching).

The issue can be fixed by not specifying an explict numerical value for `{size}` and using `max` in the IIIF standard URL: `{scheme}://{server}{/prefix}/{identifier}/{region}/{size}/{rotation}/{quality}.{format}`
Note: `{region}` should still have explicit numerical values for `x,y,w,h` just as it does already.

Reference: https://iiif.io/api/image/2.1/

**Comment by dancorpse** [comment]
Do you mean to revise the code in dezoomify for iiif images?

**Comment by mirazo** [comment]
Yes, the code in dezoomify for iiif images needs to be revised.
For example in https://github.com/lovasoa/dezoomify/issues/248 running dezoomify (http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://loris-1015814219.us-east-1.elb.amazonaws.com/loris/co5/ago.28669.jp2/info.json) complies the image as three tiles:
- http://loris-1015814219.us-east-1.elb.amazonaws.com/loris/co5/ago.28669.jp2/0,0,4180,4180/4180,4180/0/default.jpg
- http://loris-1015814219.us-east-1.elb.amazonaws.com/loris/co5/ago.28669.jp2/0,4180,4180,4180/4180,4180/0/default.jpg
- http://loris-1015814219.us-east-1.elb.amazonaws.com/loris/co5/ago.28669.jp2/0,8360,4180,4180/4180,4180/0/default.jpg

The first two are fine but the third is stretched because `{size}` is explicitly asked for as 4180x4180. The correct failsafe way would be to request the tiles as:
- http://loris-1015814219.us-east-1.elb.amazonaws.com/loris/co5/ago.28669.jp2/0,0,4180,4180/full/0/default.jpg
- http://loris-1015814219.us-east-1.elb.amazonaws.com/loris/co5/ago.28669.jp2/0,4180,4180,4180/full/0/default.jpg
- http://loris-1015814219.us-east-1.elb.amazonaws.com/loris/co5/ago.28669.jp2/0,8360,4180,4180/full/0/default.jpg

Depending on how the server is configured it may also refuse the request. Running dezoomify http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://ec2-52-2-247-250.compute-1.amazonaws.com/loris/co5/8728.jp2/info.json tries to load two tiles:
- http://ec2-52-2-247-250.compute-1.amazonaws.com/loris/co5/8728.jp2/0,0,4338,4338/4338,4338/0/default.jpg
- http://ec2-52-2-247-250.compute-1.amazonaws.com/loris/co5/8728.jp2/0,4338,4338,4338/4338,4338/0/default.jpg

The second tile fails to load (Not Found: Resolution not available 404 error). The correct failsafe way would be to request the tiles as:
- http://ec2-52-2-247-250.compute-1.amazonaws.com/loris/co5/8728.jp2/0,0,4338,4338/full/0/default.jpg
- http://ec2-52-2-247-250.compute-1.amazonaws.com/loris/co5/8728.jp2/0,4338,4338,4338/full/0/default.jpg


Note: According to https://iiif.io/api/image/2.1/ in future the `{size}` keyword `{full}` will be deprecated and replaced by `{max}` in version 3.0 but until that time some servers(like in above examples) might not be configured to accept `{max}`.

**Comment by dancorpse** [comment]
Thanks mirazo, I really wish I know coding, unfortunately I'm just a frequent user of dezoomify. Maybe we have to wait till lovasoa come here.

**Comment by lovasoa** [comment]
This should be fixed by #263. Please re-open if otherwise.

**Comment by oZarim** [comment]
Not fixed. I'd try to fix this myself but javascript really confuses me...

Once again, running dezoomify for #248 (http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://loris-1015814219.us-east-1.elb.amazonaws.com/loris/co5/ago.28669.jp2/info.json) complies the image as three tiles:

- http://loris-1015814219.us-east-1.elb.amazonaws.com/loris/co5/ago.28669.jp2/0,0,4180,4180/4180,4180/0/default.jpg
- http://loris-1015814219.us-east-1.elb.amazonaws.com/loris/co5/ago.28669.jp2/0,4180,4180,4180/4180,4180/0/default.jpg
- http://loris-1015814219.us-east-1.elb.amazonaws.com/loris/co5/ago.28669.jp2/0,8360,4180,2656/4180,2656/0/default.jpg

The first two are the same as old method, thus fine but the third now fails to load and displays error message. The correct failsafe way as mentioned before would be to request the tiles as:

- http://loris-1015814219.us-east-1.elb.amazonaws.com/loris/co5/ago.28669.jp2/0,0,4180,4180/full/0/default.jpg
- http://loris-1015814219.us-east-1.elb.amazonaws.com/loris/co5/ago.28669.jp2/0,4180,4180,4180/full/0/default.jpg
- http://loris-1015814219.us-east-1.elb.amazonaws.com/loris/co5/ago.28669.jp2/0,8360,4180,4180/full/0/default.jpg
--------------------
Same for the econd example: http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://ec2-52-2-247-250.compute-1.amazonaws.com/loris/co5/8728.jp2/info.json tries to load two tiles:

- http://ec2-52-2-247-250.compute-1.amazonaws.com/loris/co5/8728.jp2/0,0,4338,4338/4338,4338/0/default.jpg
- http://ec2-52-2-247-250.compute-1.amazonaws.com/loris/co5/8728.jp2/0,4338,4338,2090/4338,2090/0/default.jpg

The second tile fails to load using new method but with different error message. The correct failsafe way would be to request the tiles as:

- http://ec2-52-2-247-250.compute-1.amazonaws.com/loris/co5/8728.jp2/0,0,4338,4338/full/0/default.jpg
- http://ec2-52-2-247-250.compute-1.amazonaws.com/loris/co5/8728.jp2/0,4338,4338,4338/full/0/default.jpg
-----------------------------------
The example from Issue #264 (http://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://ids.lib.harvard.edu/ids/iiif/11160215/info.json) is also not resolved. Instead of getting stuck at 92% and displaying an error message it downloads the edge tiles correctly to cache but fails stitch them to final image outputting transparency on the edges. Using the new method edge tile from #264 is requested like this example:
- https://ids.lib.harvard.edu/ids/iiif/11160215/12288,7168,138,1024/138,1024/0/default.jpg

This request is allowed by the server but Dezoomify then fails to stitch it in. Correct failsafe way:
- https://ids.lib.harvard.edu/ids/iiif/11160215/12288,7168,1024,1024/full/0/default.jpg
-------------
Note still applies: According to https://iiif.io/api/image/2.1/ in future the `{size}` keyword `{full}` will be deprecated and replaced by `{max}` in version 3.0 but until that time some servers (like amazonraws in above examples) might not be configured to accept `{max}` (like the Harvard servers which do).

**Comment by noahdollar** [comment]
Hey just want to be sure I understand the issue. Tried:

http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://loris-1015814219.us-east-1.elb.amazonaws.com/loris/co5/ago.28669.jp2/info.json

and

http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://ec2-52-2-247-250.compute-1.amazonaws.com/loris/co5/8728.jp2/info.json

and

http://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://ids.lib.harvard.edu/ids/iiif/11160215/info.json

In each case, they loaded for me 100% and in the third case, it looks to me like the edges are loading completely (not seeing transparency).

Here's what I'm seeing on the top-right corner:
![image](https://user-images.githubusercontent.com/4512595/49330042-fb7bfe80-f556-11e8-8692-12e303cbaa91.png)

Again, not seeing any errors or missing tiles on this end but let me know if there's something I'm missing here.

**Comment by oZarim** [comment]
@noahdollar #263 Thanks for your code fix and reply. I didn't realise you had implemented requesting tile `{size}` using `{full}` because according to the Network Monitor in Firefox tile request URLs are still explicitly defining tile `{size}` using integer values, as mentioned in my previous post.

Since my last post, I am no longer getting error message for: (http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://loris-1015814219.us-east-1.elb.amazonaws.com/loris/co5/ago.28669.jp2/info.json) but third tile now displays transparency.

Also no longer getting error message for: (http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://ec2-52-2-247-250.compute-1.amazonaws.com/loris/co5/8728.jp2/info.json) and image displays correctly.

Still same behaviour for: (http://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://ids.lib.harvard.edu/ids/iiif/11160215/info.json). Screenshots:
![screenshot](https://user-images.githubusercontent.com/45504410/49619131-1c0ee300-f9b3-11e8-8921-0ce10b80d44a.jpg)
![screenshot1](https://user-images.githubusercontent.com/45504410/49619130-1c0ee300-f9b3-11e8-8b62-00b1b48fec06.jpg)

**Comment by noahdollar** [comment]
Oh hey, I haven't implemented any fix as of yet. Again, each of these examples loads fully for me, with no transparency and no missing tiles:
![image](https://user-images.githubusercontent.com/4512595/49652152-38d10800-f9ff-11e8-8276-e89e69c6073a.png)

Since you mentioned that individual tiles are sometimes not loading even when you go directly to them, my guess is this is probably a very unusual issue with your browser. I'd say reset your browser settings, clear cookies, do anything possible to get to a fresh browser. If that fails, I'd recommend a fresh install of Firefox and then disabling hardware acceleration (Options | Performance | Uncheck 'Use hardware acceleration when available').

**Comment by dancorpse** [comment]
Just noticed that the problem has been solved! Thanks @lovasoa and @mirazoom
