### ISSUE TITLE
Use on a site requiring log-in

### ISSUE THREAD

**Issue by justanotherbloke** [lovasoa/dezoomify#91]
http://www.britainfromabove.org.uk/image/epw006154?search=london&ref=96

Zoomify becomes active after logging-in to the site.
1. Is dezoomify available as a Firefox plug-in?
2. Is there some other way I can dezoom the image?

**Comment by lovasoa** [comment]
There is already an issue about that and is has been solved. Look at the wiki, and the closed issue.

**Comment by justanotherbloke** [comment]
Thanks for that, the information on "[How to access protected pages](url=https://github.com/lovasoa/dezoomify/wiki/How-to-access-protected-pages)" works fine, but dezoomify is still unable to acquire the image.

The site definitely uses zoomify.js, but there is no ImageProperties.xml to help.

**Comment by lovasoa** [comment]
http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://www.britainfromabove.org.uk/sites/all/lib/aerofilms-images/zoomify512/EPW/006/EPW006157/ImageProperties.xml

**Comment by lovasoa** [comment]
![canvas](https://cloud.githubusercontent.com/assets/552629/20649134/646a5270-b4d1-11e6-944b-83ff1a6717c0.jpg)
